name: freightlake
version: "1.0.0"
config-version: 2

profile: freightlake

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  freightlake:
    silver:
      +materialized: incremental
      +incremental_strategy: merge
      +schema: silver
    gold:
      +materialized: table
      +schema: gold

vars:
  catalog: "{{ env_var('DATABRICKS_CATALOG', 'freightlake') }}"

on-run-start:
  - "{{ create_udfs() if target.type == 'databricks' else '' }}"

require-dbt-version: ">=1.8.0"
